[project]
name = "physarum-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numba>=0.61.2",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "pygame>=2.6.1",
]
